// Token: 0x02000014 RID: 20
[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
public partial class Form1 : global::System.Windows.Forms.Form
{
	// Token: 0x06000080 RID: 128 RVA: 0x00006D8C File Offset: 0x00004F8C
	[global::System.Diagnostics.DebuggerStepThrough]
	private void InitializeComponent()
	{
		this.icontainer_0 = new global::System.ComponentModel.Container();
		global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Form1));
		this.ImageList_0 = new global::System.Windows.Forms.ImageList(this.icontainer_0);
		this.BackgroundWorker_0 = new global::System.ComponentModel.BackgroundWorker();
		this.BackgroundWorker_1 = new global::System.ComponentModel.BackgroundWorker();
		this.BackgroundWorker_2 = new global::System.ComponentModel.BackgroundWorker();
		this.BackgroundWorker_3 = new global::System.ComponentModel.BackgroundWorker();
		this.BackgroundWorker_4 = new global::System.ComponentModel.BackgroundWorker();
		this.BackgroundWorker_5 = new global::System.ComponentModel.BackgroundWorker();
		this.BackgroundWorker_6 = new global::System.ComponentModel.BackgroundWorker();
		this.CMP = new global::System.Windows.Forms.ContextMenuStrip(this.icontainer_0);
		this.ConfigParDefaultToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
		this.PastKeywordConfigToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
		this.ClearKeywordToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
		this.BackgroundWorker_7 = new global::System.ComponentModel.BackgroundWorker();
		this.BackgroundWorker_8 = new global::System.ComponentModel.BackgroundWorker();
		this.BackgroundWorker_9 = new global::System.ComponentModel.BackgroundWorker();
		this.ToolTip_0 = new global::System.Windows.Forms.ToolTip(this.icontainer_0);
		this.l2 = new global::System.Windows.Forms.Label();
		this.Timer_0 = new global::System.Windows.Forms.Timer(this.icontainer_0);
		this.ToolTip_1 = new global::System.Windows.Forms.ToolTip(this.icontainer_0);
		this.CERR = new global::System.Windows.Forms.Label();
		this.Label24 = new global::System.Windows.Forms.Label();
		this.Label21 = new global::System.Windows.Forms.Label();
		this.err = new global::System.Windows.Forms.Label();
		this.VisualStyler_0 = new global::SkinSoft.VisualStyler.VisualStyler(this.icontainer_0);
		this.CustomTabcontrol1 = new global::GControl0();
		this.TabPage1 = new global::System.Windows.Forms.TabPage();
		this.Button4 = new global::System.Windows.Forms.Button();
		this.RchYandex = new global::System.Windows.Forms.RichTextBox();
		this.RCHp = new global::System.Windows.Forms.RichTextBox();
		this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
		this.Button7 = new global::System.Windows.Forms.Button();
		this.Button2 = new global::System.Windows.Forms.Button();
		this.Button3 = new global::System.Windows.Forms.Button();
		this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
		this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
		this.Label20 = new global::System.Windows.Forms.Label();
		this.Label23 = new global::System.Windows.Forms.Label();
		this.CMResultat = new global::System.Windows.Forms.ComboBox();
		this.Button1 = new global::System.Windows.Forms.Button();
		this.Button6 = new global::System.Windows.Forms.Button();
		this.Label1 = new global::System.Windows.Forms.Label();
		this.TextBox4 = new global::System.Windows.Forms.TextBox();
		this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
		this.l8 = new global::System.Windows.Forms.Label();
		this.l9 = new global::System.Windows.Forms.Label();
		this.l6 = new global::System.Windows.Forms.Label();
		this.l7 = new global::System.Windows.Forms.Label();
		this.l5 = new global::System.Windows.Forms.Label();
		this.l4 = new global::System.Windows.Forms.Label();
		this.TextBox1 = new global::System.Windows.Forms.TextBox();
		this.RichTextBox6 = new global::System.Windows.Forms.RichTextBox();
		this.RichTextBox5 = new global::System.Windows.Forms.RichTextBox();
		this.RichTextBox4 = new global::System.Windows.Forms.RichTextBox();
		this.TextBox3 = new global::System.Windows.Forms.TextBox();
		this.TextBox2 = new global::System.Windows.Forms.TextBox();
		this.RichTextBox3 = new global::System.Windows.Forms.RichTextBox();
		this.RichTextBox1 = new global::System.Windows.Forms.RichTextBox();
		this.Label3 = new global::System.Windows.Forms.Label();
		this.RichTextBox2 = new global::System.Windows.Forms.RichTextBox();
		this.TabPage2 = new global::System.Windows.Forms.TabPage();
		this.TXT2 = new global::System.Windows.Forms.RichTextBox();
		this.GroupBox7 = new global::System.Windows.Forms.GroupBox();
		this.Label27 = new global::System.Windows.Forms.Label();
		this.text_proxyType = new global::System.Windows.Forms.ComboBox();
		this.bproxy = new global::System.Windows.Forms.Button();
		this.Label26 = new global::System.Windows.Forms.Label();
		this.CMType = new global::System.Windows.Forms.ComboBox();
		this.Label25 = new global::System.Windows.Forms.Label();
		this.numericUpDown1 = new global::System.Windows.Forms.NumericUpDown();
		this.BTNLoad = new global::System.Windows.Forms.Button();
		this.RichLeech = new global::System.Windows.Forms.RichTextBox();
		this.Button10 = new global::System.Windows.Forms.Button();
		this.Button9 = new global::System.Windows.Forms.Button();
		this.lbl9 = new global::System.Windows.Forms.Label();
		this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
		this.Button8 = new global::System.Windows.Forms.Button();
		this.Button5 = new global::System.Windows.Forms.Button();
		this.BTN1 = new global::System.Windows.Forms.Button();
		this.Label12 = new global::System.Windows.Forms.Label();
		this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
		this.lblc = new global::System.Windows.Forms.Label();
		this.Label2 = new global::System.Windows.Forms.Label();
		this.l12 = new global::System.Windows.Forms.Label();
		this.lbl3 = new global::System.Windows.Forms.Label();
		this.Label11 = new global::System.Windows.Forms.Label();
		this.Label13 = new global::System.Windows.Forms.Label();
		this.Label10 = new global::System.Windows.Forms.Label();
		this.Panel2 = new global::System.Windows.Forms.Panel();
		this.TabPage3 = new global::System.Windows.Forms.TabPage();
		this.Label22 = new global::System.Windows.Forms.Label();
		this.Panel1 = new global::System.Windows.Forms.Panel();
		this.Panel3 = new global::System.Windows.Forms.Panel();
		this.Label30 = new global::System.Windows.Forms.Label();
		this.PictureBox4 = new global::System.Windows.Forms.PictureBox();
		this.Label29 = new global::System.Windows.Forms.Label();
		this.Button11 = new global::System.Windows.Forms.Button();
		this.lblyes = new global::System.Windows.Forms.Label();
		this.lnews = new global::System.Windows.Forms.Label();
		this.imgversion = new global::System.Windows.Forms.PictureBox();
		this.LinkLabel4 = new global::System.Windows.Forms.LinkLabel();
		this.LinkLabel5 = new global::System.Windows.Forms.LinkLabel();
		this.LinkLabel3 = new global::System.Windows.Forms.LinkLabel();
		this.LinkLabel2 = new global::System.Windows.Forms.LinkLabel();
		this.Label28 = new global::System.Windows.Forms.Label();
		this.LinkLabel1 = new global::System.Windows.Forms.LinkLabel();
		this.Label17 = new global::System.Windows.Forms.Label();
		this.Label18 = new global::System.Windows.Forms.Label();
		this.Label19 = new global::System.Windows.Forms.Label();
		this.Label16 = new global::System.Windows.Forms.Label();
		this.Label15 = new global::System.Windows.Forms.Label();
		this.Label14 = new global::System.Windows.Forms.Label();
		this.Label9 = new global::System.Windows.Forms.Label();
		this.Label8 = new global::System.Windows.Forms.Label();
		this.Label7 = new global::System.Windows.Forms.Label();
		this.Label6 = new global::System.Windows.Forms.Label();
		this.Label5 = new global::System.Windows.Forms.Label();
		this.TextBox5 = new global::System.Windows.Forms.TextBox();
		this.Label4 = new global::System.Windows.Forms.Label();
		this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
		this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
		this.CMP.SuspendLayout();
		((global::System.ComponentModel.ISupportInitialize)this.VisualStyler_0).BeginInit();
		this.CustomTabcontrol1.SuspendLayout();
		this.TabPage1.SuspendLayout();
		this.GroupBox3.SuspendLayout();
		this.GroupBox2.SuspendLayout();
		((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
		this.GroupBox1.SuspendLayout();
		this.TabPage2.SuspendLayout();
		this.GroupBox7.SuspendLayout();
		((global::System.ComponentModel.ISupportInitialize)this.numericUpDown1).BeginInit();
		this.GroupBox5.SuspendLayout();
		this.GroupBox4.SuspendLayout();
		this.TabPage3.SuspendLayout();
		this.Panel1.SuspendLayout();
		this.Panel3.SuspendLayout();
		((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).BeginInit();
		((global::System.ComponentModel.ISupportInitialize)this.imgversion).BeginInit();
		((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
		((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
		this.SuspendLayout();
		this.ImageList_0.ImageStream = (global::System.Windows.Forms.ImageListStreamer)componentResourceManager.GetObject("IL_TabControl.ImageStream");
		this.ImageList_0.TransparentColor = global::System.Drawing.Color.Transparent;
		this.ImageList_0.Images.SetKeyName(0, "Zoom.png");
		this.ImageList_0.Images.SetKeyName(1, "icon-seo.png");
		this.ImageList_0.Images.SetKeyName(2, "Actions-help-about-icon.png");
		this.BackgroundWorker_0.WorkerSupportsCancellation = true;
		this.BackgroundWorker_1.WorkerSupportsCancellation = true;
		this.BackgroundWorker_2.WorkerSupportsCancellation = true;
		this.BackgroundWorker_3.WorkerSupportsCancellation = true;
		this.BackgroundWorker_4.WorkerSupportsCancellation = true;
		this.BackgroundWorker_5.WorkerSupportsCancellation = true;
		this.BackgroundWorker_6.WorkerSupportsCancellation = true;
		this.CMP.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
		{
			this.ConfigParDefaultToolStripMenuItem,
			this.PastKeywordConfigToolStripMenuItem,
			this.ClearKeywordToolStripMenuItem
		});
		this.CMP.Name = "CMP";
		global::System.Windows.Forms.Control cmp = this.CMP;
		global::System.Drawing.Size size = new global::System.Drawing.Size(167, 70);
		cmp.Size = size;
		this.ConfigParDefaultToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ConfigParDefaultToolStripMenuItem.Image");
		this.ConfigParDefaultToolStripMenuItem.Name = "ConfigParDefaultToolStripMenuItem";
		global::System.Windows.Forms.ToolStripItem configParDefaultToolStripMenuItem = this.ConfigParDefaultToolStripMenuItem;
		size = new global::System.Drawing.Size(166, 22);
		configParDefaultToolStripMenuItem.Size = size;
		this.ConfigParDefaultToolStripMenuItem.Text = "Default Keywords";
		this.PastKeywordConfigToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PastKeywordConfigToolStripMenuItem.Image");
		this.PastKeywordConfigToolStripMenuItem.Name = "PastKeywordConfigToolStripMenuItem";
		global::System.Windows.Forms.ToolStripItem pastKeywordConfigToolStripMenuItem = this.PastKeywordConfigToolStripMenuItem;
		size = new global::System.Drawing.Size(166, 22);
		pastKeywordConfigToolStripMenuItem.Size = size;
		this.PastKeywordConfigToolStripMenuItem.Text = "Past Keywords";
		this.ClearKeywordToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ClearKeywordToolStripMenuItem.Image");
		this.ClearKeywordToolStripMenuItem.Name = "ClearKeywordToolStripMenuItem";
		global::System.Windows.Forms.ToolStripItem clearKeywordToolStripMenuItem = this.ClearKeywordToolStripMenuItem;
		size = new global::System.Drawing.Size(166, 22);
		clearKeywordToolStripMenuItem.Size = size;
		this.ClearKeywordToolStripMenuItem.Text = "Clear Keyword";
		this.BackgroundWorker_7.WorkerSupportsCancellation = true;
		this.BackgroundWorker_8.WorkerSupportsCancellation = true;
		this.BackgroundWorker_9.WorkerSupportsCancellation = true;
		this.ToolTip_0.ToolTipIcon = global::System.Windows.Forms.ToolTipIcon.Info;
		this.l2.AutoSize = true;
		global::System.Windows.Forms.Control l = this.l2;
		global::System.Drawing.Point location = new global::System.Drawing.Point(12, 16);
		l.Location = location;
		this.l2.Name = "l2";
		global::System.Windows.Forms.Control l2 = this.l2;
		size = new global::System.Drawing.Size(59, 15);
		l2.Size = size;
		this.l2.TabIndex = 20;
		this.l2.Text = "Keyword :";
		this.ToolTip_0.SetToolTip(this.l2, "Keywords For Search");
		this.ToolTip_1.AutoPopDelay = 10000;
		this.ToolTip_1.InitialDelay = 500;
		this.ToolTip_1.IsBalloon = true;
		this.ToolTip_1.ReshowDelay = 100;
		this.ToolTip_1.ToolTipIcon = global::System.Windows.Forms.ToolTipIcon.Info;
		this.ToolTip_1.ToolTipTitle = "Those Errors Because of :";
		this.CERR.AutoSize = true;
		this.CERR.ForeColor = global::System.Drawing.Color.SlateGray;
		global::System.Windows.Forms.Control cerr = this.CERR;
		location = new global::System.Drawing.Point(200, 85);
		cerr.Location = location;
		this.CERR.Name = "CERR";
		global::System.Windows.Forms.Control cerr2 = this.CERR;
		size = new global::System.Drawing.Size(14, 15);
		cerr2.Size = size;
		this.CERR.TabIndex = 7;
		this.CERR.Text = "0";
		this.ToolTip_1.SetToolTip(this.CERR, "Websites Authorisation");
		this.Label24.AutoSize = true;
		this.Label24.ForeColor = global::System.Drawing.Color.SlateGray;
		global::System.Windows.Forms.Control label = this.Label24;
		location = new global::System.Drawing.Point(92, 85);
		label.Location = location;
		this.Label24.Name = "Label24";
		global::System.Windows.Forms.Control label2 = this.Label24;
		size = new global::System.Drawing.Size(103, 15);
		label2.Size = size;
		this.Label24.TabIndex = 6;
		this.Label24.Text = "Connexion Errors :";
		this.ToolTip_1.SetToolTip(this.Label24, "Websites Authorisation");
		this.Label21.AutoSize = true;
		this.Label21.ForeColor = global::System.Drawing.Color.RosyBrown;
		global::System.Windows.Forms.Control label3 = this.Label21;
		location = new global::System.Drawing.Point(46, 91);
		label3.Location = location;
		this.Label21.Name = "Label21";
		global::System.Windows.Forms.Control label4 = this.Label21;
		size = new global::System.Drawing.Size(98, 15);
		label4.Size = size;
		this.Label21.TabIndex = 10;
		this.Label21.Text = "Connexion Error :";
		this.ToolTip_1.SetToolTip(this.Label21, "-Websites Authorisation\r\n-Captcha\r\n-Insecure Websites..");
		this.err.AutoSize = true;
		this.err.ForeColor = global::System.Drawing.Color.RosyBrown;
		global::System.Windows.Forms.Control err = this.err;
		location = new global::System.Drawing.Point(150, 91);
		err.Location = location;
		this.err.Name = "err";
		global::System.Windows.Forms.Control err2 = this.err;
		size = new global::System.Drawing.Size(13, 15);
		err2.Size = size;
		this.err.TabIndex = 9;
		this.err.Text = "0";
		this.ToolTip_1.SetToolTip(this.err, "-Websites Authorisation\r\n-Captcha\r\n-Insecure Websites..");
		this.VisualStyler_0.License = (global::SkinSoft.VisualStyler.Licensing.VisualStylerLicense)componentResourceManager.GetObject("VisualStyler1.License");
		this.VisualStyler_0.TargetControls = global::SkinSoft.VisualStyler.TargetControls.Forms;
		this.VisualStyler_0.LoadVisualStyle(null, "Hex.vssf");
		this.CustomTabcontrol1.Alignment = global::System.Windows.Forms.TabAlignment.Left;
		this.CustomTabcontrol1.Controls.Add(this.TabPage1);
		this.CustomTabcontrol1.Controls.Add(this.TabPage2);
		this.CustomTabcontrol1.Controls.Add(this.TabPage3);
		this.CustomTabcontrol1.Dock = global::System.Windows.Forms.DockStyle.Fill;
		this.CustomTabcontrol1.DrawMode = global::System.Windows.Forms.TabDrawMode.OwnerDrawFixed;
		this.CustomTabcontrol1.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
		this.CustomTabcontrol1.ImageList = this.ImageList_0;
		global::System.Windows.Forms.TabControl customTabcontrol = this.CustomTabcontrol1;
		size = new global::System.Drawing.Size(40, 150);
		customTabcontrol.ItemSize = size;
		global::System.Windows.Forms.Control customTabcontrol2 = this.CustomTabcontrol1;
		location = new global::System.Drawing.Point(0, 0);
		customTabcontrol2.Location = location;
		this.CustomTabcontrol1.Multiline = true;
		this.CustomTabcontrol1.Name = "CustomTabcontrol1";
		this.CustomTabcontrol1.SelectedIndex = 0;
		this.CustomTabcontrol1.Color_0 = global::System.Drawing.Color.FromArgb(30, 10, 100, 200);
		this.CustomTabcontrol1.ShowToolTips = true;
		global::System.Windows.Forms.Control customTabcontrol3 = this.CustomTabcontrol1;
		size = new global::System.Drawing.Size(745, 502);
		customTabcontrol3.Size = size;
		this.CustomTabcontrol1.SizeMode = global::System.Windows.Forms.TabSizeMode.Fixed;
		this.CustomTabcontrol1.TabIndex = 0;
		this.TabPage1.Controls.Add(this.Button4);
		this.TabPage1.Controls.Add(this.RchYandex);
		this.TabPage1.Controls.Add(this.RCHp);
		this.TabPage1.Controls.Add(this.l2);
		this.TabPage1.Controls.Add(this.GroupBox3);
		this.TabPage1.Controls.Add(this.GroupBox2);
		this.TabPage1.Controls.Add(this.Label1);
		this.TabPage1.Controls.Add(this.TextBox4);
		this.TabPage1.Controls.Add(this.GroupBox1);
		this.TabPage1.Controls.Add(this.TextBox1);
		this.TabPage1.Controls.Add(this.RichTextBox6);
		this.TabPage1.Controls.Add(this.RichTextBox5);
		this.TabPage1.Controls.Add(this.RichTextBox4);
		this.TabPage1.Controls.Add(this.TextBox3);
		this.TabPage1.Controls.Add(this.TextBox2);
		this.TabPage1.Controls.Add(this.RichTextBox3);
		this.TabPage1.Controls.Add(this.RichTextBox1);
		this.TabPage1.Controls.Add(this.Label3);
		this.TabPage1.Controls.Add(this.RichTextBox2);
		this.TabPage1.Font = new global::System.Drawing.Font("Segoe UI Semibold", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		this.TabPage1.ImageKey = "Zoom.png";
		global::System.Windows.Forms.TabPage tabPage = this.TabPage1;
		location = new global::System.Drawing.Point(154, 4);
		tabPage.Location = location;
		this.TabPage1.Name = "TabPage1";
		global::System.Windows.Forms.Control tabPage2 = this.TabPage1;
		global::System.Windows.Forms.Padding padding = new global::System.Windows.Forms.Padding(3);
		tabPage2.Padding = padding;
		global::System.Windows.Forms.Control tabPage3 = this.TabPage1;
		size = new global::System.Drawing.Size(587, 494);
		tabPage3.Size = size;
		this.TabPage1.TabIndex = 0;
		this.TabPage1.Text = "Searcher";
		this.TabPage1.UseVisualStyleBackColor = true;
		this.Button4.Cursor = global::System.Windows.Forms.Cursors.Hand;
		global::System.Windows.Forms.Control button = this.Button4;
		location = new global::System.Drawing.Point(15, 463);
		button.Location = location;
		this.Button4.Name = "Button4";
		global::System.Windows.Forms.Control button2 = this.Button4;
		size = new global::System.Drawing.Size(191, 23);
		button2.Size = size;
		this.Button4.TabIndex = 23;
		this.Button4.Text = "Pass To Leecher";
		this.Button4.UseVisualStyleBackColor = true;
		this.RchYandex.BackColor = global::System.Drawing.Color.Silver;
		global::System.Windows.Forms.Control rchYandex = this.RchYandex;
		location = new global::System.Drawing.Point(690, 6);
		rchYandex.Location = location;
		this.RchYandex.Name = "RchYandex";
		global::System.Windows.Forms.Control rchYandex2 = this.RchYandex;
		size = new global::System.Drawing.Size(171, 43);
		rchYandex2.Size = size;
		this.RchYandex.TabIndex = 22;
		this.RchYandex.Text = "";
		global::System.Windows.Forms.Control rchp = this.RCHp;
		location = new global::System.Drawing.Point(1051, 3);
		rchp.Location = location;
		this.RCHp.Name = "RCHp";
		global::System.Windows.Forms.Control rchp2 = this.RCHp;
		size = new global::System.Drawing.Size(168, 47);
		rchp2.Size = size;
		this.RCHp.TabIndex = 21;
		this.RCHp.Text = "";
		this.GroupBox3.Controls.Add(this.Button7);
		this.GroupBox3.Controls.Add(this.Button2);
		this.GroupBox3.Controls.Add(this.Button3);
		global::System.Windows.Forms.Control groupBox = this.GroupBox3;
		location = new global::System.Drawing.Point(9, 319);
		groupBox.Location = location;
		this.GroupBox3.Name = "GroupBox3";
		global::System.Windows.Forms.Control groupBox2 = this.GroupBox3;
		size = new global::System.Drawing.Size(203, 138);
		groupBox2.Size = size;
		this.GroupBox3.TabIndex = 19;
		this.GroupBox3.TabStop = false;
		this.GroupBox3.Text = "Resultat option";
		this.Button7.Cursor = global::System.Windows.Forms.Cursors.Hand;
		global::System.Windows.Forms.Control button3 = this.Button7;
		location = new global::System.Drawing.Point(3, 104);
		button3.Location = location;
		this.Button7.Name = "Button7";
		global::System.Windows.Forms.Control button4 = this.Button7;
		size = new global::System.Drawing.Size(194, 24);
		button4.Size = size;
		this.Button7.TabIndex = 16;
		this.Button7.Text = "Save Resultat";
		this.Button7.UseVisualStyleBackColor = true;
		this.Button2.Cursor = global::System.Windows.Forms.Cursors.Hand;
		global::System.Windows.Forms.Control button5 = this.Button2;
		location = new global::System.Drawing.Point(3, 26);
		button5.Location = location;
		this.Button2.Name = "Button2";
		global::System.Windows.Forms.Control button6 = this.Button2;
		size = new global::System.Drawing.Size(194, 24);
		button6.Size = size;
		this.Button2.TabIndex = 14;
		this.Button2.Text = "Filtring";
		this.Button2.UseVisualStyleBackColor = true;
		this.Button3.Cursor = global::System.Windows.Forms.Cursors.Hand;
		global::System.Windows.Forms.Control button7 = this.Button3;
		location = new global::System.Drawing.Point(3, 65);
		button7.Location = location;
		this.Button3.Name = "Button3";
		global::System.Windows.Forms.Control button8 = this.Button3;
		size = new global::System.Drawing.Size(194, 24);
		button8.Size = size;
		this.Button3.TabIndex = 15;
		this.Button3.Text = "Grab";
		this.Button3.UseVisualStyleBackColor = true;
		this.GroupBox2.Controls.Add(this.PictureBox2);
		this.GroupBox2.Controls.Add(this.Label20);
		this.GroupBox2.Controls.Add(this.Label23);
		this.GroupBox2.Controls.Add(this.CMResultat);
		this.GroupBox2.Controls.Add(this.Button1);
		this.GroupBox2.Controls.Add(this.Button6);
		global::System.Windows.Forms.Control groupBox3 = this.GroupBox2;
		location = new global::System.Drawing.Point(8, 141);
		groupBox3.Location = location;
		this.GroupBox2.Name = "GroupBox2";
		global::System.Windows.Forms.Control groupBox4 = this.GroupBox2;
		size = new global::System.Drawing.Size(204, 176);
		groupBox4.Size = size;
		this.GroupBox2.TabIndex = 18;
		this.GroupBox2.TabStop = false;
		this.GroupBox2.Text = "Search Options";
		this.PictureBox2.Cursor = global::System.Windows.Forms.Cursors.Hand;
		this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
		global::System.Windows.Forms.Control pictureBox = this.PictureBox2;
		location = new global::System.Drawing.Point(118, 23);
		pictureBox.Location = location;
		this.PictureBox2.Name = "PictureBox2";
		global::System.Windows.Forms.Control pictureBox2 = this.PictureBox2;
		size = new global::System.Drawing.Size(61, 33);
		pictureBox2.Size = size;
		this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
		this.PictureBox2.TabIndex = 23;
		this.PictureBox2.TabStop = false;
		this.Label20.AutoSize = true;
		this.Label20.Font = new global::System.Drawing.Font("Calibri", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
		this.Label20.ForeColor = global::System.Drawing.Color.MidnightBlue;
		global::System.Windows.Forms.Control label5 = this.Label20;
		location = new global::System.Drawing.Point(3, 31);
		label5.Location = location;
		this.Label20.Name = "Label20";
		global::System.Windows.Forms.Control label6 = this.Label20;
		size = new global::System.Drawing.Size(116, 19);
		label6.Size = size;
		this.Label20.TabIndex = 24;
		this.Label20.Text = "Search Settings: ";
		this.Label23.AutoSize = true;
		global::System.Windows.Forms.Control label7 = this.Label23;
		location = new global::System.Drawing.Point(4, 73);
		label7.Location = location;
		this.Label23.Name = "Label23";
		global::System.Windows.Forms.Control label8 = this.Label23;
		size = new global::System.Drawing.Size(89, 15);
		label8.Size = size;
		this.Label23.TabIndex = 12;
		this.Label23.Text = "Resultat Of Last";
		this.CMResultat.Cursor = global::System.Windows.Forms.Cursors.Hand;
		this.CMResultat.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
		this.CMResultat.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
		this.CMResultat.FormattingEnabled = true;
		this.CMResultat.Items.AddRange(new object[]
		{
			"All Resultat",
			"Year",
			"Month",
			"Week",
			"24 Hour",
			"Custom"
		});
		global::System.Windows.Forms.Control cmresultat = this.CMResultat;
		location = new global::System.Drawing.Point(94, 68);
		cmresultat.Location = location;
		this.CMResultat.Name = "CMResultat";
		global::System.Windows.Forms.Control cmresultat2 = this.CMResultat;
		size = new global::System.Drawing.Size(104, 23);
		cmresultat2.Size = size;
		this.CMResultat.TabIndex = 11;
		this.Button1.Cursor = global::System.Windows.Forms.Cursors.Hand;
		global::System.Windows.Forms.Control button9 = this.Button1;
		location = new global::System.Drawing.Point(5, 103);
		button9.Location = location;
		this.Button1.Name = "Button1";
		global::System.Windows.Forms.Control button10 = this.Button1;
		size = new global::System.Drawing.Size(193, 24);
		button10.Size = size;
		this.Button1.TabIndex = 9;
		this.Button1.Text = "START";
		this.Button1.UseVisualStyleBackColor = true;
		this.Button6.Cursor = global::System.Windows.Forms.Cursors.Hand;
		this.Button6.Enabled = false;
		global::System.Windows.Forms.Control button11 = this.Button6;
		location = new global::System.Drawing.Point(5, 140);
		button11.Location = location;
		this.Button6.Name = "Button6";
		global::System.Windows.Forms.Control button12 = this.Button6;
		size = new global::System.Drawing.Size(193, 24);
		button12.Size = size;
		this.Button6.TabIndex = 10;
		this.Button6.Text = "STOP";
		this.Button6.UseVisualStyleBackColor = true;
		this.Label1.AutoSize = true;
		global::System.Windows.Forms.Control label9 = this.Label1;
		location = new global::System.Drawing.Point(379, 10);
		label9.Location = location;
		this.Label1.Name = "Label1";
		global::System.Windows.Forms.Control label10 = this.Label1;
		size = new global::System.Drawing.Size(49, 15);
		label10.Size = size;
		this.Label1.TabIndex = 17;
		this.Label1.Text = "Resultat";
		this.TextBox4.BackColor = global::System.Drawing.Color.FromArgb(30, 30, 40);
		this.TextBox4.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		this.TextBox4.ForeColor = global::System.Drawing.Color.White;
		global::System.Windows.Forms.Control textBox = this.TextBox4;
		location = new global::System.Drawing.Point(236, 28);
		textBox.Location = location;
		this.TextBox4.MaxLength = 999999999;
		this.TextBox4.Multiline = true;
		this.TextBox4.Name = "TextBox4";
		this.TextBox4.ReadOnly = true;
		this.TextBox4.ScrollBars = global::System.Windows.Forms.ScrollBars.Vertical;
		global::System.Windows.Forms.Control textBox2 = this.TextBox4;
		size = new global::System.Drawing.Size(342, 336);
		textBox2.Size = size;
		this.TextBox4.TabIndex = 16;
		this.TextBox4.Tag = "";
		this.GroupBox1.Controls.Add(this.CERR);
		this.GroupBox1.Controls.Add(this.Label24);
		this.GroupBox1.Controls.Add(this.l8);
		this.GroupBox1.Controls.Add(this.l9);
		this.GroupBox1.Controls.Add(this.l6);
		this.GroupBox1.Controls.Add(this.l7);
		this.GroupBox1.Controls.Add(this.l5);
		this.GroupBox1.Controls.Add(this.l4);
		global::System.Windows.Forms.Control groupBox5 = this.GroupBox1;
		location = new global::System.Drawing.Point(236, 370);
		groupBox5.Location = location;
		this.GroupBox1.Name = "GroupBox1";
		global::System.Windows.Forms.Control groupBox6 = this.GroupBox1;
		size = new global::System.Drawing.Size(344, 111);
		groupBox6.Size = size;
		this.GroupBox1.TabIndex = 12;
		this.GroupBox1.TabStop = false;
		this.GroupBox1.Text = "Statistics";
		this.l8.AutoSize = true;
		global::System.Windows.Forms.Control l3 = this.l8;
		location = new global::System.Drawing.Point(200, 62);
		l3.Location = location;
		this.l8.Name = "l8";
		global::System.Windows.Forms.Control l4 = this.l8;
		size = new global::System.Drawing.Size(14, 15);
		l4.Size = size;
		this.l8.TabIndex = 5;
		this.l8.Text = "0";
		this.l9.AutoSize = true;
		global::System.Windows.Forms.Control l5 = this.l9;
		location = new global::System.Drawing.Point(143, 62);
		l5.Location = location;
		this.l9.Name = "l9";
		global::System.Windows.Forms.Control l6 = this.l9;
		size = new global::System.Drawing.Size(52, 15);
		l6.Size = size;
		this.l9.TabIndex = 4;
		this.l9.Text = "Links N :";
		this.l6.AutoSize = true;
		global::System.Windows.Forms.Control l7 = this.l6;
		location = new global::System.Drawing.Point(200, 39);
		l7.Location = location;
		this.l6.Name = "l6";
		global::System.Windows.Forms.Control l8 = this.l6;
		size = new global::System.Drawing.Size(14, 15);
		l8.Size = size;
		this.l6.TabIndex = 3;
		this.l6.Text = "0";
		this.l7.AutoSize = true;
		global::System.Windows.Forms.Control l9 = this.l7;
		location = new global::System.Drawing.Point(134, 39);
		l9.Location = location;
		this.l7.Name = "l7";
		global::System.Windows.Forms.Control l10 = this.l7;
		size = new global::System.Drawing.Size(61, 15);
		l10.Size = size;
		this.l7.TabIndex = 2;
		this.l7.Text = "A.Filtring :";
		this.l5.AutoSize = true;
		global::System.Windows.Forms.Control l11 = this.l5;
		location = new global::System.Drawing.Point(200, 17);
		l11.Location = location;
		this.l5.Name = "l5";
		global::System.Windows.Forms.Control l12 = this.l5;
		size = new global::System.Drawing.Size(14, 15);
		l12.Size = size;
		this.l5.TabIndex = 1;
		this.l5.Text = "0";
		this.l4.AutoSize = true;
		global::System.Windows.Forms.Control l13 = this.l4;
		location = new global::System.Drawing.Point(140, 16);
		l13.Location = location;
		this.l4.Name = "l4";
		global::System.Windows.Forms.Control l14 = this.l4;
		size = new global::System.Drawing.Size(55, 15);
		l14.Size = size;
		this.l4.TabIndex = 0;
		this.l4.Text = "Resultat :";
		this.TextBox1.BackColor = global::System.Drawing.Color.FromArgb(30, 30, 40);
		this.TextBox1.ContextMenuStrip = this.CMP;
		this.TextBox1.ForeColor = global::System.Drawing.Color.White;
		global::System.Windows.Forms.Control textBox3 = this.TextBox1;
		location = new global::System.Drawing.Point(9, 34);
		textBox3.Location = location;
		this.TextBox1.MaxLength = 999999999;
		this.TextBox1.Multiline = true;
		this.TextBox1.Name = "TextBox1";
		this.TextBox1.ScrollBars = global::System.Windows.Forms.ScrollBars.Vertical;
		global::System.Windows.Forms.Control textBox4 = this.TextBox1;
		size = new global::System.Drawing.Size(203, 101);
		textBox4.Size = size;
		this.TextBox1.TabIndex = 11;
		global::System.Windows.Forms.Control richTextBox = this.RichTextBox6;
		location = new global::System.Drawing.Point(876, 242);
		richTextBox.Location = location;
		this.RichTextBox6.Name = "RichTextBox6";
		global::System.Windows.Forms.Control richTextBox2 = this.RichTextBox6;
		size = new global::System.Drawing.Size(168, 47);
		richTextBox2.Size = size;
		this.RichTextBox6.TabIndex = 8;
		this.RichTextBox6.Text = "";
		global::System.Windows.Forms.Control richTextBox3 = this.RichTextBox5;
		location = new global::System.Drawing.Point(879, 426);
		richTextBox3.Location = location;
		this.RichTextBox5.Name = "RichTextBox5";
		global::System.Windows.Forms.Control richTextBox4 = this.RichTextBox5;
		size = new global::System.Drawing.Size(168, 47);
		richTextBox4.Size = size;
		this.RichTextBox5.TabIndex = 7;
		this.RichTextBox5.Text = "";
		global::System.Windows.Forms.Control richTextBox5 = this.RichTextBox4;
		location = new global::System.Drawing.Point(876, 189);
		richTextBox5.Location = location;
		this.RichTextBox4.Name = "RichTextBox4";
		global::System.Windows.Forms.Control richTextBox6 = this.RichTextBox4;
		size = new global::System.Drawing.Size(174, 47);
		richTextBox6.Size = size;
		this.RichTextBox4.TabIndex = 6;
		this.RichTextBox4.Text = "";
		global::System.Windows.Forms.Control textBox5 = this.TextBox3;
		location = new global::System.Drawing.Point(876, 367);
		textBox5.Location = location;
		this.TextBox3.Multiline = true;
		this.TextBox3.Name = "TextBox3";
		global::System.Windows.Forms.Control textBox6 = this.TextBox3;
		size = new global::System.Drawing.Size(174, 53);
		textBox6.Size = size;
		this.TextBox3.TabIndex = 5;
		global::System.Windows.Forms.Control textBox7 = this.TextBox2;
		location = new global::System.Drawing.Point(876, 308);
		textBox7.Location = location;
		this.TextBox2.Multiline = true;
		this.TextBox2.Name = "TextBox2";
		global::System.Windows.Forms.Control textBox8 = this.TextBox2;
		size = new global::System.Drawing.Size(174, 53);
		textBox8.Size = size;
		this.TextBox2.TabIndex = 4;
		global::System.Windows.Forms.Control richTextBox7 = this.RichTextBox3;
		location = new global::System.Drawing.Point(876, 108);
		richTextBox7.Location = location;
		this.RichTextBox3.Name = "RichTextBox3";
		global::System.Windows.Forms.Control richTextBox8 = this.RichTextBox3;
		size = new global::System.Drawing.Size(174, 75);
		richTextBox8.Size = size;
		this.RichTextBox3.TabIndex = 3;
		this.RichTextBox3.Text = "";
		this.RichTextBox1.BackColor = global::System.Drawing.Color.Silver;
		global::System.Windows.Forms.Control richTextBox9 = this.RichTextBox1;
		location = new global::System.Drawing.Point(876, 6);
		richTextBox9.Location = location;
		this.RichTextBox1.Name = "RichTextBox1";
		global::System.Windows.Forms.Control richTextBox10 = this.RichTextBox1;
		size = new global::System.Drawing.Size(171, 43);
		richTextBox10.Size = size;
		this.RichTextBox1.TabIndex = 1;
		this.RichTextBox1.Text = "";
		this.Label3.AutoSize = true;
		global::System.Windows.Forms.Control label11 = this.Label3;
		location = new global::System.Drawing.Point(10, 591);
		label11.Location = location;
		this.Label3.Name = "Label3";
		global::System.Windows.Forms.Control label12 = this.Label3;
		size = new global::System.Drawing.Size(98, 15);
		label12.Size = size;
		this.Label3.TabIndex = 0;
		this.Label3.Text = "Config/Keywords";
		global::System.Windows.Forms.Control richTextBox11 = this.RichTextBox2;
		location = new global::System.Drawing.Point(876, 55);
		richTextBox11.Location = location;
		this.RichTextBox2.Name = "RichTextBox2";
		global::System.Windows.Forms.Control richTextBox12 = this.RichTextBox2;
		size = new global::System.Drawing.Size(168, 47);
		richTextBox12.Size = size;
		this.RichTextBox2.TabIndex = 2;
		this.RichTextBox2.Text = "";
		this.TabPage2.Controls.Add(this.TXT2);
		this.TabPage2.Controls.Add(this.GroupBox7);
		this.TabPage2.Controls.Add(this.RichLeech);
		this.TabPage2.Controls.Add(this.Button10);
		this.TabPage2.Controls.Add(this.Button9);
		this.TabPage2.Controls.Add(this.lbl9);
		this.TabPage2.Controls.Add(this.GroupBox5);
		this.TabPage2.Controls.Add(this.Label12);
		this.TabPage2.Controls.Add(this.GroupBox4);
		this.TabPage2.Controls.Add(this.Label10);
		this.TabPage2.Controls.Add(this.Panel2);
		this.TabPage2.ImageIndex = 1;
		global::System.Windows.Forms.TabPage tabPage4 = this.TabPage2;
		location = new global::System.Drawing.Point(154, 4);
		tabPage4.Location = location;
		this.TabPage2.Name = "TabPage2";
		global::System.Windows.Forms.Control tabPage5 = this.TabPage2;
		padding = new global::System.Windows.Forms.Padding(3);
		tabPage5.Padding = padding;
		global::System.Windows.Forms.Control tabPage6 = this.TabPage2;
		size = new global::System.Drawing.Size(587, 494);
		tabPage6.Size = size;
		this.TabPage2.TabIndex = 1;
		this.TabPage2.Text = "Leecher";
		this.TabPage2.UseVisualStyleBackColor = true;
		this.TXT2.BackColor = global::System.Drawing.Color.FromArgb(30, 30, 40);
		this.TXT2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
		this.TXT2.ForeColor = global::System.Drawing.Color.White;
		global::System.Windows.Forms.Control txt = this.TXT2;
		location = new global::System.Drawing.Point(262, 32);
		txt.Location = location;
		this.TXT2.Name = "TXT2";
		this.TXT2.ReadOnly = true;
		global::System.Windows.Forms.Control txt2 = this.TXT2;
		size = new global::System.Drawing.Size(317, 397);
		txt2.Size = size;
		this.TXT2.TabIndex = 15;
		this.TXT2.Text = "";
		this.GroupBox7.Controls.Add(this.Label27);
		this.GroupBox7.Controls.Add(this.text_proxyType);
		this.GroupBox7.Controls.Add(this.bproxy);
		this.GroupBox7.Controls.Add(this.Label26);
		this.GroupBox7.Controls.Add(this.CMType);
		this.GroupBox7.Controls.Add(this.Label25);
		this.GroupBox7.Controls.Add(this.numericUpDown1);
		this.GroupBox7.Controls.Add(this.BTNLoad);
		global::System.Windows.Forms.Control groupBox7 = this.GroupBox7;
		location = new global::System.Drawing.Point(11, 24);
		groupBox7.Location = location;
		this.GroupBox7.Name = "GroupBox7";
		global::System.Windows.Forms.Control groupBox8 = this.GroupBox7;
		size = new global::System.Drawing.Size(237, 197);
		groupBox8.Size = size;
		this.GroupBox7.TabIndex = 14;
		this.GroupBox7.TabStop = false;
		this.GroupBox7.Text = "Result Options";
		this.Label27.AutoSize = true;
		global::System.Windows.Forms.Control label13 = this.Label27;
		location = new global::System.Drawing.Point(7, 99);
		label13.Location = location;
		this.Label27.Name = "Label27";
		global::System.Windows.Forms.Control label14 = this.Label27;
		size = new global::System.Drawing.Size(71, 15);
		label14.Size = size;
		this.Label27.TabIndex = 17;
		this.Label27.Text = "Proxy Type :";
		this.text_proxyType.Cursor = global::System.Windows.Forms.Cursors.Hand;
		this.text_proxyType.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
		this.text_proxyType.FormattingEnabled = true;
		this.text_proxyType.Items.AddRange(new object[]
		{
			"HTTP/HTTPS",
			"SOCKS4",
			"SOCKS5",
			"NO PROXY"
		});
		global::System.Windows.Forms.Control text_proxyType = this.text_proxyType;
		location = new global::System.Drawing.Point(80, 96);
		text_proxyType.Location = location;
		this.text_proxyType.Name = "text_proxyType";
		global::System.Windows.Forms.Control text_proxyType2 = this.text_proxyType;
		size = new global::System.Drawing.Size(141, 23);
		text_proxyType2.Size = size;
		this.text_proxyType.TabIndex = 16;
		this.bproxy.AllowDrop = true;
		this.bproxy.Cursor = global::System.Windows.Forms.Cursors.Hand;
		this.bproxy.Enabled = false;
		global::System.Windows.Forms.Control bproxy = this.bproxy;
		location = new global::System.Drawing.Point(15, 59);
		bproxy.Location = location;
		this.bproxy.Name = "bproxy";
		global::System.Windows.Forms.Control bproxy2 = this.bproxy;
		size = new global::System.Drawing.Size(206, 26);
		bproxy2.Size = size;
		this.bproxy.TabIndex = 15;
		this.bproxy.Text = "Load Proxy";
		this.bproxy.UseVisualStyleBackColor = true;
		this.Label26.AutoSize = true;
		global::System.Windows.Forms.Control label15 = this.Label26;
		location = new global::System.Drawing.Point(7, 134);
		label15.Location = location;
		this.Label26.Name = "Label26";
		global::System.Windows.Forms.Control label16 = this.Label26;
		size = new global::System.Drawing.Size(71, 15);
		label16.Size = size;
		this.Label26.TabIndex = 14;
		this.Label26.Text = "Result type :";
		this.CMType.Cursor = global::System.Windows.Forms.Cursors.Hand;
		this.CMType.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
		this.CMType.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
		this.CMType.FormattingEnabled = true;
		this.CMType.Items.AddRange(new object[]
		{
			"Email:Password Combo",
			"Mailst(Emails)",
			"User:Password Combo",
			"Custom Regex"
		});
		global::System.Windows.Forms.Control cmtype = this.CMType;
		location = new global::System.Drawing.Point(80, 130);
		cmtype.Location = location;
		this.CMType.Name = "CMType";
		global::System.Windows.Forms.Control cmtype2 = this.CMType;
		size = new global::System.Drawing.Size(141, 23);
		cmtype2.Size = size;
		this.CMType.TabIndex = 12;
		this.Label25.AutoSize = true;
		global::System.Windows.Forms.Control label17 = this.Label25;
		location = new global::System.Drawing.Point(12, 170);
		label17.Location = location;
		this.Label25.Name = "Label25";
		global::System.Windows.Forms.Control label18 = this.Label25;
		size = new global::System.Drawing.Size(55, 15);
		label18.Size = size;
		this.Label25.TabIndex = 11;
		this.Label25.Text = "Threads :";
		this.numericUpDown1.Cursor = global::System.Windows.Forms.Cursors.Hand;
		global::System.Windows.Forms.Control numericUpDown = this.numericUpDown1;
		location = new global::System.Drawing.Point(73, 164);
		numericUpDown.Location = location;
		global::System.Windows.Forms.NumericUpDown numericUpDown2 = this.numericUpDown1;
		decimal num = new decimal(new int[]
		{
			200,
			0,
			0,
			0
		});
		numericUpDown2.Maximum = num;
		global::System.Windows.Forms.NumericUpDown numericUpDown3 = this.numericUpDown1;
		num = new decimal(new int[]
		{
			50,
			0,
			0,
			0
		});
		numericUpDown3.Minimum = num;
		this.numericUpDown1.Name = "numericUpDown1";
		global::System.Windows.Forms.Control numericUpDown4 = this.numericUpDown1;
		size = new global::System.Drawing.Size(140, 23);
		numericUpDown4.Size = size;
		this.numericUpDown1.TabIndex = 13;
		this.numericUpDown1.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
		global::System.Windows.Forms.NumericUpDown numericUpDown5 = this.numericUpDown1;
		num = new decimal(new int[]
		{
			50,
			0,
			0,
			0
		});
		numericUpDown5.Value = num;
		this.BTNLoad.AllowDrop = true;
		this.BTNLoad.Cursor = global::System.Windows.Forms.Cursors.Hand;
		global::System.Windows.Forms.Control btnload = this.BTNLoad;
		location = new global::System.Drawing.Point(15, 22);
		btnload.Location = location;
		this.BTNLoad.Name = "BTNLoad";
		global::System.Windows.Forms.Control btnload2 = this.BTNLoad;
		size = new global::System.Drawing.Size(206, 26);
		btnload2.Size = size;
		this.BTNLoad.TabIndex = 3;
		this.BTNLoad.Text = "Load Links";
		this.BTNLoad.UseVisualStyleBackColor = true;
		global::System.Windows.Forms.Control richLeech = this.RichLeech;
		location = new global::System.Drawing.Point(602, 24);
		richLeech.Location = location;
		this.RichLeech.Name = "RichLeech";
		global::System.Windows.Forms.Control richLeech2 = this.RichLeech;
		size = new global::System.Drawing.Size(433, 375);
		richLeech2.Size = size;
		this.RichLeech.TabIndex = 9;
		this.RichLeech.Text = "";
		this.RichLeech.Visible = false;
		this.Button10.Cursor = global::System.Windows.Forms.Cursors.Hand;
		global::System.Windows.Forms.Control button13 = this.Button10;
		location = new global::System.Drawing.Point(431, 435);
		button13.Location = location;
		this.Button10.Name = "Button10";
		global::System.Windows.Forms.Control button14 = this.Button10;
		size = new global::System.Drawing.Size(149, 32);
		button14.Size = size;
		this.Button10.TabIndex = 7;
		this.Button10.Text = "Remove Duplicates";
		this.Button10.UseVisualStyleBackColor = true;
		this.Button9.Cursor = global::System.Windows.Forms.Cursors.Hand;
		global::System.Windows.Forms.Control button15 = this.Button9;
		location = new global::System.Drawing.Point(262, 436);
		button15.Location = location;
		this.Button9.Name = "Button9";
		global::System.Windows.Forms.Control button16 = this.Button9;
		size = new global::System.Drawing.Size(149, 32);
		button16.Size = size;
		this.Button9.TabIndex = 6;
		this.Button9.Text = "Clear Reultat";
		this.Button9.UseVisualStyleBackColor = true;
		this.lbl9.AutoSize = true;
		global::System.Windows.Forms.Control lbl = this.lbl9;
		location = new global::System.Drawing.Point(56, 476);
		lbl.Location = location;
		this.lbl9.Name = "lbl9";
		global::System.Windows.Forms.Control lbl2 = this.lbl9;
		size = new global::System.Drawing.Size(17, 15);
		lbl2.Size = size;
		this.lbl9.TabIndex = 5;
		this.lbl9.Text = "--";
		this.GroupBox5.Controls.Add(this.Button8);
		this.GroupBox5.Controls.Add(this.Button5);
		this.GroupBox5.Controls.Add(this.BTN1);
		global::System.Windows.Forms.Control groupBox9 = this.GroupBox5;
		location = new global::System.Drawing.Point(8, 219);
		groupBox9.Location = location;
		this.GroupBox5.Name = "GroupBox5";
		global::System.Windows.Forms.Control groupBox10 = this.GroupBox5;
		size = new global::System.Drawing.Size(234, 132);
		groupBox10.Size = size;
		this.GroupBox5.TabIndex = 5;
		this.GroupBox5.TabStop = false;
		this.GroupBox5.Text = "Option";
		this.Button8.Cursor = global::System.Windows.Forms.Cursors.Hand;
		global::System.Windows.Forms.Control button17 = this.Button8;
		location = new global::System.Drawing.Point(16, 99);
		button17.Location = location;
		this.Button8.Name = "Button8";
		global::System.Windows.Forms.Control button18 = this.Button8;
		size = new global::System.Drawing.Size(208, 26);
		button18.Size = size;
		this.Button8.TabIndex = 2;
		this.Button8.Text = "Save Resultat";
		this.Button8.UseVisualStyleBackColor = true;
		this.Button5.Cursor = global::System.Windows.Forms.Cursors.Hand;
		this.Button5.Enabled = false;
		global::System.Windows.Forms.Control button19 = this.Button5;
		location = new global::System.Drawing.Point(16, 60);
		button19.Location = location;
		this.Button5.Name = "Button5";
		global::System.Windows.Forms.Control button20 = this.Button5;
		size = new global::System.Drawing.Size(208, 26);
		button20.Size = size;
		this.Button5.TabIndex = 1;
		this.Button5.Text = "STOP";
		this.Button5.UseVisualStyleBackColor = true;
		this.BTN1.Cursor = global::System.Windows.Forms.Cursors.Hand;
		global::System.Windows.Forms.Control btn = this.BTN1;
		location = new global::System.Drawing.Point(16, 21);
		btn.Location = location;
		this.BTN1.Name = "BTN1";
		global::System.Windows.Forms.Control btn2 = this.BTN1;
		size = new global::System.Drawing.Size(208, 26);
		btn2.Size = size;
		this.BTN1.TabIndex = 0;
		this.BTN1.Text = "START";
		this.BTN1.UseVisualStyleBackColor = true;
		this.Label12.AutoSize = true;
		global::System.Windows.Forms.Control label19 = this.Label12;
		location = new global::System.Drawing.Point(5, 475);
		label19.Location = location;
		this.Label12.Name = "Label12";
		global::System.Windows.Forms.Control label20 = this.Label12;
		size = new global::System.Drawing.Size(45, 15);
		label20.Size = size;
		this.Label12.TabIndex = 4;
		this.Label12.Text = "Status :";
		this.GroupBox4.Controls.Add(this.Label21);
		this.GroupBox4.Controls.Add(this.err);
		this.GroupBox4.Controls.Add(this.lblc);
		this.GroupBox4.Controls.Add(this.Label2);
		this.GroupBox4.Controls.Add(this.l12);
		this.GroupBox4.Controls.Add(this.lbl3);
		this.GroupBox4.Controls.Add(this.Label11);
		this.GroupBox4.Controls.Add(this.Label13);
		global::System.Windows.Forms.Control groupBox11 = this.GroupBox4;
		location = new global::System.Drawing.Point(11, 353);
		groupBox11.Location = location;
		this.GroupBox4.Name = "GroupBox4";
		global::System.Windows.Forms.Control groupBox12 = this.GroupBox4;
		size = new global::System.Drawing.Size(234, 115);
		groupBox12.Size = size;
		this.GroupBox4.TabIndex = 4;
		this.GroupBox4.TabStop = false;
		this.GroupBox4.Text = "Statistics";
		this.lblc.AutoSize = true;
		global::System.Windows.Forms.Control lblc = this.lblc;
		location = new global::System.Drawing.Point(150, 41);
		lblc.Location = location;
		this.lblc.Name = "lblc";
		global::System.Windows.Forms.Control lblc2 = this.lblc;
		size = new global::System.Drawing.Size(13, 15);
		lblc2.Size = size;
		this.lblc.TabIndex = 8;
		this.lblc.Text = "0";
		this.Label2.AutoSize = true;
		global::System.Windows.Forms.Control label21 = this.Label2;
		location = new global::System.Drawing.Point(62, 65);
		label21.Location = location;
		this.Label2.Name = "Label2";
		global::System.Windows.Forms.Control label22 = this.Label2;
		size = new global::System.Drawing.Size(82, 15);
		label22.Size = size;
		this.Label2.TabIndex = 7;
		this.Label2.Text = "Used Link (n) :";
		this.l12.AutoSize = true;
		global::System.Windows.Forms.Control l15 = this.l12;
		location = new global::System.Drawing.Point(150, 66);
		l15.Location = location;
		this.l12.Name = "l12";
		global::System.Windows.Forms.Control l16 = this.l12;
		size = new global::System.Drawing.Size(13, 15);
		l16.Size = size;
		this.l12.TabIndex = 6;
		this.l12.Text = "0";
		this.lbl3.AutoSize = true;
		global::System.Windows.Forms.Control lbl3 = this.lbl3;
		location = new global::System.Drawing.Point(150, 17);
		lbl3.Location = location;
		this.lbl3.Name = "lbl3";
		global::System.Windows.Forms.Control lbl4 = this.lbl3;
		size = new global::System.Drawing.Size(13, 15);
		lbl4.Size = size;
		this.lbl3.TabIndex = 2;
		this.lbl3.Text = "0";
		this.Label11.AutoSize = true;
		global::System.Windows.Forms.Control label23 = this.Label11;
		location = new global::System.Drawing.Point(89, 40);
		label23.Location = location;
		this.Label11.Name = "Label11";
		global::System.Windows.Forms.Control label24 = this.Label11;
		size = new global::System.Drawing.Size(55, 15);
		label24.Size = size;
		this.Label11.TabIndex = 1;
		this.Label11.Text = "Resultat :";
		this.Label13.AutoSize = true;
		global::System.Windows.Forms.Control label25 = this.Label13;
		location = new global::System.Drawing.Point(62, 15);
		label25.Location = location;
		this.Label13.Name = "Label13";
		global::System.Windows.Forms.Control label26 = this.Label13;
		size = new global::System.Drawing.Size(82, 15);
		label26.Size = size;
		this.Label13.TabIndex = 0;
		this.Label13.Text = "Loaded Links :";
		global::System.Windows.Forms.Control label27 = this.Label10;
		location = new global::System.Drawing.Point(263, 7);
		label27.Location = location;
		this.Label10.Name = "Label10";
		global::System.Windows.Forms.Control label28 = this.Label10;
		size = new global::System.Drawing.Size(318, 15);
		label28.Size = size;
		this.Label10.TabIndex = 2;
		this.Label10.Text = "Results";
		this.Label10.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
		this.Panel2.BackColor = global::System.Drawing.Color.FromArgb(198, 221, 231);
		this.Panel2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
		global::System.Windows.Forms.Control panel = this.Panel2;
		location = new global::System.Drawing.Point(262, 32);
		panel.Location = location;
		this.Panel2.Name = "Panel2";
		global::System.Windows.Forms.Control panel2 = this.Panel2;
		size = new global::System.Drawing.Size(318, 364);
		panel2.Size = size;
		this.Panel2.TabIndex = 16;
		this.TabPage3.BackColor = global::System.Drawing.SystemColors.ButtonFace;
		this.TabPage3.Controls.Add(this.Label22);
		this.TabPage3.Controls.Add(this.Panel1);
		this.TabPage3.Controls.Add(this.LinkLabel4);
		this.TabPage3.Controls.Add(this.LinkLabel5);
		this.TabPage3.Controls.Add(this.LinkLabel3);
		this.TabPage3.Controls.Add(this.LinkLabel2);
		this.TabPage3.Controls.Add(this.Label28);
		this.TabPage3.Controls.Add(this.LinkLabel1);
		this.TabPage3.Controls.Add(this.Label17);
		this.TabPage3.Controls.Add(this.Label18);
		this.TabPage3.Controls.Add(this.Label19);
		this.TabPage3.Controls.Add(this.Label16);
		this.TabPage3.Controls.Add(this.Label15);
		this.TabPage3.Controls.Add(this.Label14);
		this.TabPage3.Controls.Add(this.Label9);
		this.TabPage3.Controls.Add(this.Label8);
		this.TabPage3.Controls.Add(this.Label7);
		this.TabPage3.Controls.Add(this.Label6);
		this.TabPage3.Controls.Add(this.Label5);
		this.TabPage3.Controls.Add(this.TextBox5);
		this.TabPage3.Controls.Add(this.Label4);
		this.TabPage3.Controls.Add(this.PictureBox1);
		this.TabPage3.Controls.Add(this.PictureBox3);
		this.TabPage3.ImageKey = "icon3.ico";
		global::System.Windows.Forms.TabPage tabPage7 = this.TabPage3;
		location = new global::System.Drawing.Point(154, 4);
		tabPage7.Location = location;
		this.TabPage3.Name = "TabPage3";
		global::System.Windows.Forms.Control tabPage8 = this.TabPage3;
		padding = new global::System.Windows.Forms.Padding(3);
		tabPage8.Padding = padding;
		global::System.Windows.Forms.Control tabPage9 = this.TabPage3;
		size = new global::System.Drawing.Size(587, 494);
		tabPage9.Size = size;
		this.TabPage3.TabIndex = 2;
		this.TabPage3.Text = "About Coder";
		this.Label22.AutoSize = true;
		this.Label22.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control label29 = this.Label22;
		location = new global::System.Drawing.Point(24, 390);
		label29.Location = location;
		this.Label22.Name = "Label22";
		global::System.Windows.Forms.Control label30 = this.Label22;
		size = new global::System.Drawing.Size(73, 15);
		label30.Size = size;
		this.Label22.TabIndex = 20;
		this.Label22.Text = "Donate xD :";
		this.Panel1.BackColor = global::System.Drawing.SystemColors.Control;
		this.Panel1.Controls.Add(this.Panel3);
		this.Panel1.Controls.Add(this.Button11);
		this.Panel1.Controls.Add(this.lblyes);
		this.Panel1.Controls.Add(this.lnews);
		this.Panel1.Controls.Add(this.imgversion);
		this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Bottom;
		global::System.Windows.Forms.Control panel3 = this.Panel1;
		location = new global::System.Drawing.Point(3, 418);
		panel3.Location = location;
		this.Panel1.Name = "Panel1";
		global::System.Windows.Forms.Control panel4 = this.Panel1;
		size = new global::System.Drawing.Size(581, 73);
		panel4.Size = size;
		this.Panel1.TabIndex = 18;
		this.Panel3.Controls.Add(this.Label30);
		this.Panel3.Controls.Add(this.PictureBox4);
		this.Panel3.Controls.Add(this.Label29);
		this.Panel3.Dock = global::System.Windows.Forms.DockStyle.Fill;
		global::System.Windows.Forms.Control panel5 = this.Panel3;
		location = new global::System.Drawing.Point(0, 0);
		panel5.Location = location;
		this.Panel3.Name = "Panel3";
		global::System.Windows.Forms.Control panel6 = this.Panel3;
		size = new global::System.Drawing.Size(581, 73);
		panel6.Size = size;
		this.Panel3.TabIndex = 4;
		this.Label30.AutoSize = true;
		this.Label30.Font = new global::System.Drawing.Font("Calibri", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control label31 = this.Label30;
		location = new global::System.Drawing.Point(416, 56);
		label31.Location = location;
		this.Label30.Name = "Label30";
		global::System.Windows.Forms.Control label32 = this.Label30;
		size = new global::System.Drawing.Size(160, 14);
		label32.Size = size;
		this.Label30.TabIndex = 1;
		this.Label30.Text = "Copyright © X-SLAYER , Tunisia";
		this.PictureBox4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox4.Image");
		global::System.Windows.Forms.Control pictureBox3 = this.PictureBox4;
		location = new global::System.Drawing.Point(4, 25);
		pictureBox3.Location = location;
		this.PictureBox4.Name = "PictureBox4";
		global::System.Windows.Forms.Control pictureBox4 = this.PictureBox4;
		size = new global::System.Drawing.Size(19, 22);
		pictureBox4.Size = size;
		this.PictureBox4.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
		this.PictureBox4.TabIndex = 1;
		this.PictureBox4.TabStop = false;
		this.Label29.AutoSize = true;
		this.Label29.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		this.Label29.ForeColor = global::System.Drawing.Color.Red;
		global::System.Windows.Forms.Control label33 = this.Label29;
		location = new global::System.Drawing.Point(28, 28);
		label33.Location = location;
		this.Label29.Name = "Label29";
		global::System.Windows.Forms.Control label34 = this.Label29;
		size = new global::System.Drawing.Size(351, 17);
		label34.Size = size;
		this.Label29.TabIndex = 0;
		this.Label29.Text = "I am not responsible for its use in the event of a failure\r\n";
		this.Button11.Cursor = global::System.Windows.Forms.Cursors.Hand;
		this.Button11.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control button21 = this.Button11;
		location = new global::System.Drawing.Point(418, 24);
		button21.Location = location;
		this.Button11.Name = "Button11";
		global::System.Windows.Forms.Control button22 = this.Button11;
		size = new global::System.Drawing.Size(140, 30);
		button22.Size = size;
		this.Button11.TabIndex = 3;
		this.Button11.Text = "Check For Updates";
		this.Button11.UseVisualStyleBackColor = true;
		this.lblyes.AutoSize = true;
		this.lblyes.Cursor = global::System.Windows.Forms.Cursors.Hand;
		this.lblyes.ForeColor = global::System.Drawing.Color.FromArgb(28, 28, 28);
		global::System.Windows.Forms.Control lblyes = this.lblyes;
		location = new global::System.Drawing.Point(69, 42);
		lblyes.Location = location;
		this.lblyes.Name = "lblyes";
		global::System.Windows.Forms.Control lblyes2 = this.lblyes;
		size = new global::System.Drawing.Size(64, 15);
		lblyes2.Size = size;
		this.lblyes.TabIndex = 2;
		this.lblyes.Text = "Version 0.3";
		this.lnews.AutoSize = true;
		this.lnews.Cursor = global::System.Windows.Forms.Cursors.Hand;
		this.lnews.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control lnews = this.lnews;
		location = new global::System.Drawing.Point(67, 16);
		lnews.Location = location;
		this.lnews.Name = "lnews";
		global::System.Windows.Forms.Control lnews2 = this.lnews;
		size = new global::System.Drawing.Size(154, 15);
		lnews2.Size = size;
		this.lnews.TabIndex = 1;
		this.lnews.Text = "This Version Is Up-To-Date";
		this.imgversion.Cursor = global::System.Windows.Forms.Cursors.Hand;
		this.imgversion.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("imgversion.Image");
		global::System.Windows.Forms.Control imgversion = this.imgversion;
		location = new global::System.Drawing.Point(4, 7);
		imgversion.Location = location;
		this.imgversion.Name = "imgversion";
		global::System.Windows.Forms.Control imgversion2 = this.imgversion;
		size = new global::System.Drawing.Size(62, 54);
		imgversion2.Size = size;
		this.imgversion.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
		this.imgversion.TabIndex = 0;
		this.imgversion.TabStop = false;
		this.LinkLabel4.AutoSize = true;
		global::System.Windows.Forms.Control linkLabel = this.LinkLabel4;
		location = new global::System.Drawing.Point(103, 390);
		linkLabel.Location = location;
		this.LinkLabel4.Name = "LinkLabel4";
		global::System.Windows.Forms.Control linkLabel2 = this.LinkLabel4;
		size = new global::System.Drawing.Size(239, 15);
		linkLabel2.Size = size;
		this.LinkLabel4.TabIndex = 19;
		this.LinkLabel4.TabStop = true;
		this.LinkLabel4.Text = "1BwmJGbs7gJXHE4wfYbBhqBQQpFbCaKY9j";
		this.LinkLabel5.AutoSize = true;
		global::System.Windows.Forms.Control linkLabel3 = this.LinkLabel5;
		location = new global::System.Drawing.Point(114, 362);
		linkLabel3.Location = location;
		this.LinkLabel5.Name = "LinkLabel5";
		global::System.Windows.Forms.Control linkLabel4 = this.LinkLabel5;
		size = new global::System.Drawing.Size(59, 15);
		linkLabel4.Size = size;
		this.LinkLabel5.TabIndex = 15;
		this.LinkLabel5.TabStop = true;
		this.LinkLabel5.Text = "X-SLAYER";
		this.LinkLabel3.AutoSize = true;
		global::System.Windows.Forms.Control linkLabel5 = this.LinkLabel3;
		location = new global::System.Drawing.Point(78, 334);
		linkLabel5.Location = location;
		this.LinkLabel3.Name = "LinkLabel3";
		global::System.Windows.Forms.Control linkLabel6 = this.LinkLabel3;
		size = new global::System.Drawing.Size(59, 15);
		linkLabel6.Size = size;
		this.LinkLabel3.TabIndex = 15;
		this.LinkLabel3.TabStop = true;
		this.LinkLabel3.Text = "X-SLAYER";
		this.LinkLabel2.AutoSize = true;
		global::System.Windows.Forms.Control linkLabel7 = this.LinkLabel2;
		location = new global::System.Drawing.Point(78, 306);
		linkLabel7.Location = location;
		this.LinkLabel2.Name = "LinkLabel2";
		global::System.Windows.Forms.Control linkLabel8 = this.LinkLabel2;
		size = new global::System.Drawing.Size(117, 15);
		linkLabel8.Size = size;
		this.LinkLabel2.TabIndex = 14;
		this.LinkLabel2.TabStop = true;
		this.LinkLabel2.Text = "Iheb Briki | X-SLAYER";
		this.Label28.AutoSize = true;
		this.Label28.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control label35 = this.Label28;
		location = new global::System.Drawing.Point(17, 362);
		label35.Location = location;
		this.Label28.Name = "Label28";
		global::System.Windows.Forms.Control label36 = this.Label28;
		size = new global::System.Drawing.Size(96, 15);
		label36.Size = size;
		this.Label28.TabIndex = 14;
		this.Label28.Text = "Facebook Page :";
		this.LinkLabel1.AutoSize = true;
		global::System.Windows.Forms.Control linkLabel9 = this.LinkLabel1;
		location = new global::System.Drawing.Point(78, 278);
		linkLabel9.Location = location;
		this.LinkLabel1.Name = "LinkLabel1";
		global::System.Windows.Forms.Control linkLabel10 = this.LinkLabel1;
		size = new global::System.Drawing.Size(56, 15);
		linkLabel10.Size = size;
		this.LinkLabel1.TabIndex = 13;
		this.LinkLabel1.TabStop = true;
		this.LinkLabel1.Text = "Iheb Briki";
		this.Label17.AutoSize = true;
		this.Label17.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control label37 = this.Label17;
		location = new global::System.Drawing.Point(16, 334);
		label37.Location = location;
		this.Label17.Name = "Label17";
		global::System.Windows.Forms.Control label38 = this.Label17;
		size = new global::System.Drawing.Size(59, 15);
		label38.Size = size;
		this.Label17.TabIndex = 12;
		this.Label17.Text = "Youtube :";
		this.Label18.AutoSize = true;
		this.Label18.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control label39 = this.Label18;
		location = new global::System.Drawing.Point(24, 306);
		label39.Location = location;
		this.Label18.Name = "Label18";
		global::System.Windows.Forms.Control label40 = this.Label18;
		size = new global::System.Drawing.Size(51, 15);
		label40.Size = size;
		this.Label18.TabIndex = 11;
		this.Label18.Text = "Twitter:";
		this.Label19.AutoSize = true;
		this.Label19.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control label41 = this.Label19;
		location = new global::System.Drawing.Point(9, 278);
		label41.Location = location;
		this.Label19.Name = "Label19";
		global::System.Windows.Forms.Control label42 = this.Label19;
		size = new global::System.Drawing.Size(66, 15);
		label42.Size = size;
		this.Label19.TabIndex = 10;
		this.Label19.Text = "Facebook :";
		this.Label16.AutoSize = true;
		this.Label16.Font = new global::System.Drawing.Font("Calibri", 14.25f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Underline, global::System.Drawing.GraphicsUnit.Point, 0);
		this.Label16.ForeColor = global::System.Drawing.Color.Maroon;
		global::System.Windows.Forms.Control label43 = this.Label16;
		location = new global::System.Drawing.Point(14, 246);
		label43.Location = location;
		this.Label16.Name = "Label16";
		global::System.Windows.Forms.Control label44 = this.Label16;
		size = new global::System.Drawing.Size(210, 23);
		label44.Size = size;
		this.Label16.TabIndex = 9;
		this.Label16.Text = "Feel Free To Contact Me :";
		this.Label15.AutoSize = true;
		this.Label15.Font = new global::System.Drawing.Font("Segoe UI Semibold", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control label45 = this.Label15;
		location = new global::System.Drawing.Point(82, 216);
		label45.Location = location;
		this.Label15.Name = "Label15";
		global::System.Windows.Forms.Control label46 = this.Label15;
		size = new global::System.Drawing.Size(59, 15);
		label46.Size = size;
		this.Label15.TabIndex = 8;
		this.Label15.Text = "X-SLAYER";
		this.Label14.AutoSize = true;
		this.Label14.Font = new global::System.Drawing.Font("Segoe UI Semibold", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control label47 = this.Label14;
		location = new global::System.Drawing.Point(82, 184);
		label47.Location = location;
		this.Label14.Name = "Label14";
		global::System.Windows.Forms.Control label48 = this.Label14;
		size = new global::System.Drawing.Size(24, 15);
		label48.Size = size;
		this.Label14.TabIndex = 7;
		this.Label14.Text = "0.6";
		this.Label9.AutoSize = true;
		this.Label9.Font = new global::System.Drawing.Font("Segoe UI Semibold", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control label49 = this.Label9;
		location = new global::System.Drawing.Point(82, 152);
		label49.Location = location;
		this.Label9.Name = "Label9";
		global::System.Windows.Forms.Control label50 = this.Label9;
		size = new global::System.Drawing.Size(91, 15);
		label50.Size = size;
		this.Label9.TabIndex = 6;
		this.Label9.Text = "SLAYER Leecher";
		this.Label8.AutoSize = true;
		this.Label8.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control label51 = this.Label8;
		location = new global::System.Drawing.Point(11, 216);
		label51.Location = location;
		this.Label8.Name = "Label8";
		global::System.Windows.Forms.Control label52 = this.Label8;
		size = new global::System.Drawing.Size(65, 15);
		label52.Size = size;
		this.Label8.TabIndex = 5;
		this.Label8.Text = "Coded By :";
		this.Label7.AutoSize = true;
		this.Label7.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control label53 = this.Label7;
		location = new global::System.Drawing.Point(22, 184);
		label53.Location = location;
		this.Label7.Name = "Label7";
		global::System.Windows.Forms.Control label54 = this.Label7;
		size = new global::System.Drawing.Size(54, 15);
		label54.Size = size;
		this.Label7.TabIndex = 4;
		this.Label7.Text = "Version :";
		this.Label6.AutoSize = true;
		this.Label6.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control label55 = this.Label6;
		location = new global::System.Drawing.Point(23, 152);
		label55.Location = location;
		this.Label6.Name = "Label6";
		global::System.Windows.Forms.Control label56 = this.Label6;
		size = new global::System.Drawing.Size(53, 15);
		label56.Size = size;
		this.Label6.TabIndex = 3;
		this.Label6.Text = "Project :";
		this.Label5.AutoSize = true;
		this.Label5.Font = new global::System.Drawing.Font("Calibri", 14.25f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Underline, global::System.Drawing.GraphicsUnit.Point, 0);
		this.Label5.ForeColor = global::System.Drawing.Color.Maroon;
		global::System.Windows.Forms.Control label57 = this.Label5;
		location = new global::System.Drawing.Point(18, 113);
		label57.Location = location;
		this.Label5.Name = "Label5";
		global::System.Windows.Forms.Control label58 = this.Label5;
		size = new global::System.Drawing.Size(143, 23);
		label58.Size = size;
		this.Label5.TabIndex = 2;
		this.Label5.Text = "About Software :";
		this.TextBox5.BackColor = global::System.Drawing.SystemColors.Control;
		this.TextBox5.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
		this.TextBox5.Font = new global::System.Drawing.Font("Impact", 20.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
		global::System.Windows.Forms.Control textBox9 = this.TextBox5;
		location = new global::System.Drawing.Point(261, 43);
		textBox9.Location = location;
		this.TextBox5.Name = "TextBox5";
		this.TextBox5.ReadOnly = true;
		global::System.Windows.Forms.Control textBox10 = this.TextBox5;
		size = new global::System.Drawing.Size(136, 33);
		textBox10.Size = size;
		this.TextBox5.TabIndex = 1;
		this.TextBox5.Text = "By X-SLAYER";
		this.Label4.AutoSize = true;
		this.Label4.Font = new global::System.Drawing.Font("Impact", 21.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
		this.Label4.ForeColor = global::System.Drawing.Color.Blue;
		global::System.Windows.Forms.Control label59 = this.Label4;
		location = new global::System.Drawing.Point(17, 8);
		label59.Location = location;
		this.Label4.Name = "Label4";
		global::System.Windows.Forms.Control label60 = this.Label4;
		size = new global::System.Drawing.Size(234, 36);
		label60.Size = size;
		this.Label4.TabIndex = 0;
		this.Label4.Text = "SLAYER Leecher v 6";
		this.PictureBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
		this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
		global::System.Windows.Forms.Control pictureBox5 = this.PictureBox1;
		location = new global::System.Drawing.Point(123, 63);
		pictureBox5.Location = location;
		this.PictureBox1.Name = "PictureBox1";
		global::System.Windows.Forms.Control pictureBox6 = this.PictureBox1;
		size = new global::System.Drawing.Size(493, 380);
		pictureBox6.Size = size;
		this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
		this.PictureBox1.TabIndex = 19;
		this.PictureBox1.TabStop = false;
		this.PictureBox3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox3.Image");
		global::System.Windows.Forms.Control pictureBox7 = this.PictureBox3;
		location = new global::System.Drawing.Point(123, 63);
		pictureBox7.Location = location;
		this.PictureBox3.Name = "PictureBox3";
		global::System.Windows.Forms.Control pictureBox8 = this.PictureBox3;
		size = new global::System.Drawing.Size(493, 368);
		pictureBox8.Size = size;
		this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
		this.PictureBox3.TabIndex = 20;
		this.PictureBox3.TabStop = false;
		this.AllowDrop = true;
		global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(7f, 13f);
		this.AutoScaleDimensions = autoScaleDimensions;
		this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
		size = new global::System.Drawing.Size(745, 502);
		this.ClientSize = size;
		this.Controls.Add(this.CustomTabcontrol1);
		this.Cursor = global::System.Windows.Forms.Cursors.Arrow;
		this.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
		this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
		this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
		this.MaximizeBox = false;
		this.Name = "Form1";
		this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
		this.Text = "SLAYER Leecher v0.6";
		this.CMP.ResumeLayout(false);
		((global::System.ComponentModel.ISupportInitialize)this.VisualStyler_0).EndInit();
		this.CustomTabcontrol1.ResumeLayout(false);
		this.TabPage1.ResumeLayout(false);
		this.TabPage1.PerformLayout();
		this.GroupBox3.ResumeLayout(false);
		this.GroupBox2.ResumeLayout(false);
		this.GroupBox2.PerformLayout();
		((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
		this.GroupBox1.ResumeLayout(false);
		this.GroupBox1.PerformLayout();
		this.TabPage2.ResumeLayout(false);
		this.TabPage2.PerformLayout();
		this.GroupBox7.ResumeLayout(false);
		this.GroupBox7.PerformLayout();
		((global::System.ComponentModel.ISupportInitialize)this.numericUpDown1).EndInit();
		this.GroupBox5.ResumeLayout(false);
		this.GroupBox4.ResumeLayout(false);
		this.GroupBox4.PerformLayout();
		this.TabPage3.ResumeLayout(false);
		this.TabPage3.PerformLayout();
		this.Panel1.ResumeLayout(false);
		this.Panel1.PerformLayout();
		this.Panel3.ResumeLayout(false);
		this.Panel3.PerformLayout();
		((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).EndInit();
		((global::System.ComponentModel.ISupportInitialize)this.imgversion).EndInit();
		((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
		((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
		this.ResumeLayout(false);
	}

	// Token: 0x04000042 RID: 66
	private global::System.ComponentModel.IContainer icontainer_0;
}
